name: Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:`pwd`/flutter/bin"
      
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get packages
        run: flutter pub get

      - name: Build package
        run: flutter pub publish --dry-run

      - name: Publish package
        run: flutter pub publish
